variable "prod-lt-name" {}
variable "ami-redhat-id" {}
variable "instance_type" {}
variable "prod-lt-sg" {}
variable "keypair_name" {}
variable "prod-asg-name" {}
variable "vpc-zone-identifier" {}
variable "tg-arn" {}
variable "asg-policy" {}
variable "nexus-ip" {}
